### Create Room
POST http://127.0.0.1:23123/rpc
Content-Type: application/json

{
  "method": "createRoom",
  "params": {"name":  "JohnDoe"},
  "id":"5555"
}

> {%
client.global.set("roomKey", response.body.result.roomKey)
client.global.set("playerKey", response.body.result.playerKey)
client.global.set("playerSecret", response.body.result.playerSecret)
 %}

### Join Room
POST http://127.0.0.1:23123/rpc
Content-Type: application/json

{
  "method": "joinRoom",
  "params": {"roomKey":  "{{roomKey}}", "name":  "Rabbitt87"},
  "id":"5555"
}

> {%
client.global.set("playerKey", response.body.result.playerKey)
client.global.set("playerSecret", response.body.result.playerSecret)
%}

### Update Room
POST http://127.0.0.1:23123/rpc
Content-Type: application/json

{
  "method": "updateRoom",
  "params": {"area":  [[49.795007,9.892073],
[49.802597,9.909925],
[49.802707,9.916363],
[49.803151,9.925718],
[49.804646,9.936190],
[49.804979,9.951725],
[49.795672,9.967861],
[49.790186,9.970350],
[49.790186,9.963999],
[49.777994,9.954729],
[49.777384,9.961081],
[49.770234,9.959021],
[49.771786,9.951811],
[49.773338,9.943657],
[49.772562,9.938335],
[49.775389,9.932241],
[49.785531,9.927092],
[49.793566,9.926147],
[49.790851,9.907608],
[49.789410,9.898338],
[49.794453,9.892845]], "numberOfQuestions":  2, "playerKey": "{{playerKey}}", "roomKey": "{{roomKey}}", "playerSecret":  "{{playerSecret}}"},
  "id":"5555"
}

### Start Game
POST http://127.0.0.1:23123/rpc
Content-Type: application/json

{
  "method": "startGame",
  "params": {"playerKey": "{{playerKey}}", "roomKey": "{{roomKey}}", "playerSecret": "{{playerSecret}}"},
  "id": "5555"
}

### Answer Question
POST http://127.0.0.1:23123/rpc
Content-Type: application/json

{
  "method": "answerQuestion",
  "params": {"playerKey": "{{playerKey}}", "roomKey": "{{roomKey}}", "guess": [49.7970, 9.8982], "playerSecret":  "{{playerSecret}}"},
  "id": "5555"
}

### Listen on Events

WEBSOCKET ws://127.0.0.1:23123/ws/{{roomKey}}/{{playerKey}}
ckc-player-secret: {{playerSecret}}
