### Create Room
POST http://127.0.0.1:23123/rpc
Content-Type: application/json

{
  "method": "createRoom",
  "params": {
    "name": "JohnDoe"
  },
  "id": "5555"
}

> {%
  client.global.set("roomKey", response.body.result.roomKey)
  client.global.set("playerKey", response.body.result.playerKey)
  client.global.set("playerSecret", response.body.result.playerSecret)
%}

### Join Room
POST http://127.0.0.1:23123/rpc
Content-Type: application/json

{
  "method": "joinRoom",
  "params": {"roomKey":  "{{roomKey}}", "name":  "Rabbitt87"},
  "id":"5555"
}

> {%
  client.global.set("playerKey", response.body.result.playerKey)
  client.global.set("playerSecret", response.body.result.playerSecret)
%}

### Update Room
POST http://127.0.0.1:23123/rpc
Content-Type: application/json

{
  "method": "updateRoom",
  "params": {"listFileName": "wuerzburg.json", "numberOfQuestions":  2, "playerKey": "{{playerKey}}", "roomKey": "{{roomKey}}", "playerSecret":  "{{playerSecret}}","maxAnswerTimeSec": 10 },
  "id":"5555"
}

### Get available street lists
POST http://127.0.0.1:23123/rpc
Content-Type: application/json

{
  "method": "getAvailableStreetLists",
  "params": {},
  "id": "5555"
}

### Start Game
POST http://127.0.0.1:23123/rpc
Content-Type: application/json

{
  "method": "startGame",
  "params": {"playerKey": "{{playerKey}}", "roomKey": "{{roomKey}}", "playerSecret": "{{playerSecret}}"},
  "id": "5555"
}

### Answer Question
POST http://127.0.0.1:23123/rpc
Content-Type: application/json

{
  "method": "answerQuestion",
  "params": {"playerKey": "{{playerKey}}", "roomKey": "{{roomKey}}", "guess": [49.7970, 9.8982], "playerSecret":  "{{playerSecret}}"},
  "id": "5555"
}

### Advance Game
POST http://127.0.0.1:23123/rpc
Content-Type: application/json

{
  "method": "advanceGame",
  "params": {"playerKey": "{{playerKey}}", "roomKey": "{{roomKey}}", "playerSecret": "{{playerSecret}}"},
  "id": "5555"
}


### Listen on Events

WEBSOCKET ws://127.0.0.1:23123/ws/{{roomKey}}/{{playerKey}}
ckc-player-secret: {{playerSecret}}

### Listen on statistic events

WEBSOCKET ws://127.0.0.1:23123/wsstatistics/abc
